# Generated by Django 4.2.21 on 2025-09-10 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_updates', models.BooleanField(default=True)),
                ('new_content', models.BooleanField(default=True)),
                ('deadline_reminders', models.BooleanField(default=True)),
                ('live_session_reminders', models.BooleanField(default=True)),
                ('forum_replies', models.BooleanField(default=True)),
                ('mentions', models.BooleanField(default=True)),
                ('certificate_issued', models.BooleanField(default=True)),
                ('course_completed', models.BooleanField(default=True)),
                ('progress_reports', models.BooleanField(default=True)),
                ('user_reports', models.BooleanField(default=True)),
                ('system_alerts', models.BooleanField(default=True)),
                ('course_approvals', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('COURSE', 'Course Related'), ('SYSTEM', 'System Notification'), ('CERTIFICATE', 'Certificate'), ('ASSESSMENT', 'Assessment'), ('SOCIAL', 'Social Interaction'), ('ADMIN', 'Admin Alert')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('related_content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
