# Generated by Django 4.2.21 on 2025-09-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_survey_surveyresponse_surveyquestion_surveychoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='text_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
