# Generated by Django 4.2.21 on 2025-05-12 17:39

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('LOGIN', 'User Login'), ('COURSE_VIEW', 'Course View'), ('LESSON_START', 'Lesson Started'), ('LESSON_COMPLETE', 'Lesson Completed'), ('QUIZ_ATTEMPT', 'Quiz Attempt'), ('CERTIFICATE_EARNED', 'Certificate Earned')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
    ]
