# Generated by Django 4.2.21 on 2025-08-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsection',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('VIDEO', 'Video')], default='TEXT', max_length=10),
        ),
        migrations.AddField(
            model_name='lessonsection',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
