# Generated by Django 4.2.21 on 2025-08-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lessonsection_content_type_lessonsection_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
