# Generated by Django 4.2.21 on 2025-05-12 17:39

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('education', models.TextField()),
                ('innovation', models.TextField()),
                ('innovation_stage', models.TextField()),
                ('innovation_in_whitebox', models.TextField()),
                ('innovation_industry', models.TextField()),
                ('training', models.TextField()),
                ('training_institution', models.TextField()),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('date_registered', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('LEARNER', 'Learner'), ('CONTENT_MANAGER', 'Content Manager'), ('ADMIN', 'Administrator')], default='LEARNER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
