# Generated by Django 4.2.21 on 2025-07-22 16:32

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 16, 32, 16, 426094, tzinfo=datetime.timezone.utc)),
        ),
    ]
