# Generated by Django 4.2.21 on 2025-08-09 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_verified_user_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 10, 17, 58, 51, 73147, tzinfo=datetime.timezone.utc)),
        ),
    ]
