# Generated by Django 4.2.21 on 2025-08-12 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_verification_token_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 16, 57, 18, 196059, tzinfo=datetime.timezone.utc)),
        ),
    ]
