# Generated by Django 4.2.21 on 2025-08-14 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_verification_token_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 15, 8, 19, 27, 260365, tzinfo=datetime.timezone.utc)),
        ),
    ]
