# Generated by Django 4.2.21 on 2025-09-09 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_date_registered_remove_user_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 10, 18, 38, 28, 507712, tzinfo=datetime.timezone.utc)),
        ),
    ]
