# Generated by Django 4.2.21 on 2025-09-11 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_verification_token_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 12, 9, 3, 13, 409402, tzinfo=datetime.timezone.utc)),
        ),
    ]
