# Generated by Django 4.2.21 on 2025-09-11 16:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_first_login_notification_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_token_expires',
            field=models.DateTimeField(default=users.models.default_verification_expiry),
        ),
    ]
